
//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

namespace LibA
{
    public class ComponentRegistry : StructureMap.Configuration.DSL.Registry
    {
        public ComponentRegistry()
        {
            Profile("Request", p => p.For(typeof(LibA.IMagicWand)).Singleton().Use(typeof(LibA.MagicWand)));
        }
    }
}

